# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wod',
            old_name='wod_id',
            new_name='wod_url',
        ),
    ]
